---
name: Trigger test

on:
  issue_comment:
    types:
      - created

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: prepare
        run: |
          echo "prepare"

  step1:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          whatareyoudoing!

  step2:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: step2
        run: |
          echo "step2"

  trigger-step:
    needs: [prepare, step1, step2]
    runs-on: ubuntu-latest
    steps:
      - name: trigger
        run: |
          echo "trigger"

