---
name: Fedora compose trigger

on:
  issue_comment:
    types:
      - created

env:
  COMPOSE_URL_F43: https://dl.fedoraproject.org/pub/fedora/linux/development/43
  COMPOSE_URL_RAWHIDE: https://dl.fedoraproject.org/pub/fedora/linux/development/rawhide

jobs:
  check-compose:
    runs-on: self-hosted
    container: quay.io/fedora/fedora:43-x86_64
    steps:
      - run: sudo dnf install -y git gh

      - uses: actions/checkout@v3

