---
name: Greenboot ci

on:
  push:
    branches:
      - main

jobs:
  greenboot-ci-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Check info
        run: |
          sudo pwd
          sudo ls
      - name: Checkout images code
        uses: actions/checkout@v3
        with:
          repository: say-paul/images
          ref: remove-old-greenboot-services
          path: images
      - name: Check info
        run: |
          sudo pwd
          sudo ls
      - name: Checkout osbuild-composer code
        run: git clone https://github.com/osbuild/osbuild-composer.git
      - name: Check info
        run: |
          sudo pwd
          sudo ls
      - name: Run greenboottest
        run: ./test1.sh
