---
name: Test trigger

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  COMPOSE_URL_CS9: https://odcs.stream.centos.org/production/

jobs:
  check-compose:
    if: ${{ github.event.issue.pull_request || (endsWith(github.event.comment.body, '/test')) }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - run: sudo dnf install -y gh

      - name: Check CentOS Stream 9 compose
        id: check_compose_id_cs9
        run: |
          echo "cs9_compose=12345" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

