# name: Tests

# on:
#   pull_request:
#     branches:
#       - "*"

# jobs:
#   shellcheck:
#     name: "🐚 Shellcheck"
#     runs-on: ubuntu-20.04
#     steps:
#     - uses: actions/checkout@v2
#       with:
#         ref: ${{ github.event.pull_request.head.sha }}
#     - name: Run ShellCheck
#       uses: ludeeus/action-shellcheck@0.5.0
#       with:
#         ignore: vendor # We don't want to fix the code in vendored dependencies
#       env:
#         SHELLCHECK_OPTS: -e SC1091 -e SC2002 # don't check /etc/os-release sourcing and allow useless cats to live inside our codebase
