---
name: CI test on sub-branch

on:
  issue_comment:
    types:
      - created

jobs:
  pr-info:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "This is to test sub-branch"