# ---
# name: CentOS Stream compose trigger

# on:
#   issue_comment:
#     types:
#       - created

# on:
#   issue_comment:
#     types: [created]
#   pull_request:
#     types: [opened, synchronize, reopened]

# env:
#   COMPOSE_URL_CS9: https://odcs.stream.centos.org/production/

# jobs:
#   check-compose:
#     if: ${{ github.event.issue.pull_request || (endsWith(github.event.comment.body, '/test')) }}
#     runs-on: self-hosted
#     steps:
#       - uses: actions/checkout@v3

#       - run: sudo dnf install -y gh

#       - name: Check CentOS Stream 9 compose
#         id: check_compose_id_cs9
#         run: |
#           echo "cs9_compose=12345" >> $GITHUB_OUTPUT
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#     outputs:
#       cs9_compose: ${{ steps.check_compose_id_cs9.outputs.cs9_compose }}
#       osbuild_version_cs9: ${{ steps.check_compose_id_cs9.outputs.osbuild_version_cs9 }}
#       osbuild_composer_version_cs9: ${{ steps.check_compose_id_cs9.outputs.osbuild_composer_version_cs9 }}
#       composer_cli_version_cs9: ${{ steps.check_compose_id_cs9.outputs.composer_cli_version_cs9 }}
#       updated_pkgs: ${{ steps.check_compose_id_cs9.outputs.updated_pkgs }}
#       count: ${{ steps.check_compose_id_cs9.outputs.count }}

#   centos-stream-9:
#     needs: check-compose
#     if: ${{ needs.check-compose.outputs.cs9_compose != 'false' }}
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3

#       - name: Add new compose id in compose.cs9
#         run: |
#           compose_id="${{ needs.check-compose.outputs.cs9_compose }}"
#           echo $compose_id >> compose/compose.cs9
#           cat compose/compose.cs9

#       - name: Get current date
#         id: date
#         run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

#       - name: Create Pull Request
#         id: cpr
#         uses: peter-evans/create-pull-request@v4
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           commit-message: "${{ needs.check-compose.outputs.cs9_compose }} - ${{ steps.date.outputs.date }}"
#           committer: cloudkitebot <henrywangxf1@gmail.com>
#           author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
#           branch: cpr
#           branch-suffix: random
#           delete-branch: true
#           title: "${{ needs.check-compose.outputs.cs9_compose }} - ${{ steps.date.outputs.date }}"
#           labels: auto-merge,CentOS-Stream-9
#           body: |
#             CentOS Stream 9 compose ${{ needs.check-compose.outputs.cs9_compose }}
#             - Date: ${{ steps.date.outputs.date }}
#             - Osbuild version:
#                 - ${{ needs.check-compose.outputs.osbuild_version_cs9 }}
#                 - ${{ needs.check-compose.outputs.osbuild_composer_version_cs9 }}
#                 - ${{ needs.check-compose.outputs.composer_cli_version_cs9 }}
#             - Updated packages(${{ needs.check-compose.outputs.count }}):
#                   ${{ needs.check-compose.outputs.updated_pkgs }}

#       - name: Add a comment to trigger test workflow
#         uses: peter-evans/create-or-update-comment@v2
#         with:
#           token: ${{ secrets.PAT }}
#           issue-number: ${{ steps.cpr.outputs.pull-request-number }}
#           body: /test-cs9
