---
name: RHEL 9 compose package trigger

on:
  issues:
    types:
      - opened

env:
  COMPOSE_URL_95: "http://download-node-02.eng.bos.redhat.com/rhel-9/nightly/updates/RHEL-9"
  PACKAGES_95: (acl alternatives audit-libs avahi-libs basesystem bash bzip2-libs)

jobs:
  check-compose:
    # Do not run this job on any fork repos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check RHEL 9.5 compose
        id: check_compose_id_95
        run: |
          curl -s http://download-node-02.eng.bos.redhat.com/rhel-9/nightly/updates/RHEL-9/latest-RHEL-9.5.0/COMPOSE_ID --output COMPOSE_ID_95
          COMPOSE_ID_95=$(cat COMPOSE_ID_95)
          echo "rhel95_compose=$COMPOSE_ID_95"

          for pkg in (acl alternatives audit-libs avahi-libs basesystem bash bzip2-libs)
          do
            v=$(curl -s "http://download-node-02.eng.bos.redhat.com/rhel-9/nightly/updates/RHEL-9/${COMPOSE_ID_95}/compose/AppStream/x86_64/os/Packages/" | grep -ioE ">${pkg}-[0-9].*<" | tr -d "><")
            echo $v
          done
