---
name: Greenboot Test on Fedora 40

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  fedora-40-bootc-qcow2:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4
        with:
          ref: ${{ needs.pr-info.outputs.sha }}
          fetch-depth: 0

      - name: Run the tests
        run: |
          sudo apt install libkrb5-dev pkg-config libvirt-dev genisoimage qemu-kvm libvirt-daemon-system --fix-missing
          pip install --user "tmt[provision]"
          sudo systemctl start libvirtd
          
